services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    volumes:
      - .:/cube/conf
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=trino
      - CUBEJS_DB_HOST=databasetycoon-free-cluster.trino.galaxy.starburst.io
      - CUBEJS_DB_USER=stephen@databasetycoon.com/accountadmin
      - CUBEJS_DB_PASS=${STARBURST_CLUSTER_PASSWORD}
      - CUBEJS_DB_PRESTO_CATALOG=dbtycoon_renegade
      - CUBEJS_DB_NAME=dbt

  evidence:
    image: evidencedev/devenv:latest
    ports:
      - "3000:3000"
    volumes:
      - ./evidence:/evidence
    working_dir: /evidence
    environment:
      - NODE_ENV=development
    depends_on:
      - cube
networks:
  default:
    name: renegade-network 
