services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    volumes:
      - .:/cube/conf
      - ./cube/model:/cube/model
      - ./data:/data
    environment:
      - CUBEJS_DB_TYPE=trino
      - CUBEJS_DB_HOST=databasetycoon.galaxy.starburst.io
      - CUBEJS_DB_USER=stephen@databasetycoon.com
      - CUBEJS_DB_PASS=XJM7qap9rhe@dmd4xaz
      - CUBEJS_DB_PRESTO_CATALOG=dbtycoon_renegade
      - CUBEJS_DB_SCHEMA=nyc_open_data
      - CUBEJS_DEV_MODE=true

  evidence:
    image: evidencedev/devenv:latest
    ports:
      - "3000:3000"
    volumes:
      - ./evidence:/evidence
    working_dir: /evidence
    environment:
      - NODE_ENV=development
    depends_on:
      - cube

networks:
  default:
    name: renegade-network 
