services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=duckdb
      - CUBEJS_SCHEMA_PATH=/cube/model
      - CUBEJS_DB_DUCKDB_DATABASE_PATH=nyc_open_data_pipeline.duckdb # path to the database file, change to s3 or local path
    volumes:
      - ../:/cube/conf
      - ./model:/cube/model
    ## if host OS is Lunux
    # network_mode: 'host'